FROM    golang:1.11.4-alpine as builder
RUN     apk add -U git

ARG     FILEWATCHER=v0.3.2
RUN     go get -d github.com/dnephin/filewatcher && \
        cd /go/src/github.com/dnephin/filewatcher && \
        git checkout -q "$FILEWATCHER" && \
        go install .

ARG     LINT=v1.12.5
RUN     go get -d github.com/golangci/golangci-lint/cmd/golangci-lint && \
        cd /go/src/github.com/golangci/golangci-lint && \
        git checkout -q "$LINT" && \
        go install ./cmd/golangci-lint

ARG		COUNTERFEITER=d7285d544cff
RUN		go get -d github.com/maxbrunsfeld/counterfeiter && \
		cd /go/src/github.com/maxbrunsfeld/counterfeiter && \
		git checkout -q "$COUNTERFEITER" && \
		go install .

ARG		GOTESTSUM=v0.3.2
RUN		go get -d gotest.tools/gotestsum && \
		cd /go/src/gotest.tools/gotestsum && \
		git checkout -q "$GOTESTSUM" && \
		go install .

ARG     BINDATA=a0ff2567cfb70903282db057e799fd826784d41d
RUN     go get -d github.com/dantoml/go-bindata && \
        mv /go/src/github.com/dantoml /go/src/github.com/jteeuwen && \
        cd /go/src/github.com/jteeuwen/go-bindata && \
        git checkout -q "$BINDATA" && \
        go install ./go-bindata

ARG     PROTOC=v1.1.0
RUN     go get -d github.com/golang/protobuf/protoc-gen-go && \
        cd /go/src/github.com/golang/protobuf && \
        git checkout -q "$PROTOC" && \
        go install ./protoc-gen-go

FROM    golang:1.11.4-alpine
RUN     apk add -U \
            curl git bash openssh-client make \
            protobuf \
            docker
RUN		git config --global url."https://github.com/".insteadOf 'git@github.com:'
RUN		mkdir -p /root/.ssh && ssh-keyscan github.com > /root/.ssh/known_hosts

COPY	--from=builder /go/bin /usr/local/bin
RUN     mkdir /opt && \
        ln -s /go/src/github.com/circleci/build-agent/workdir /opt/circleci
ENV     PS1="# "
WORKDIR /go/src/github.com/circleci/build-agent
ENV     GO111MODULE=on
ENV		BUILDTAGS="" CGO_ENABLED=0
