FROM    golang:1.10-alpine as builder
RUN     apk add -U git

ARG     FILEWATCHER=v0.3.0
RUN     go get -d github.com/dnephin/filewatcher && \
        cd /go/src/github.com/dnephin/filewatcher && \
        git checkout -q "$FILEWATCHER" && \
        go install .

ARG     DEP=v0.4.1
RUN     go get -d github.com/golang/dep/cmd/dep && \
        cd /go/src/github.com/golang/dep && \
        git checkout -q "$DEP" && \
        go install ./cmd/dep

ARG     GOMETALINTER=v2.0.5
RUN     go get -d github.com/alecthomas/gometalinter && \
        cd /go/src/github.com/alecthomas/gometalinter && \
        git checkout -q "$GOMETALINTER" && \
        go install . && \
        /go/bin/gometalinter --install

ARG		COUNTERFEITER=c1996179167e70f7a863c4d04dcaa6981109afed
RUN		go get -d github.com/maxbrunsfeld/counterfeiter && \
		cd /go/src/github.com/maxbrunsfeld/counterfeiter && \
		git checkout -q "$COUNTERFEITER" && \
		go install .

ARG		GOTESTSUM=v0.3.0
RUN		go get -d gotest.tools/gotestsum && \
		cd /go/src/gotest.tools/gotestsum && \
		git checkout -q "$GOTESTSUM" && \
		go install .

ARG     BINDATA=a0ff2567cfb70903282db057e799fd826784d41d
RUN     go get -d github.com/dantoml/go-bindata && \
        mv /go/src/github.com/dantoml /go/src/github.com/jteeuwen && \
        cd /go/src/github.com/jteeuwen/go-bindata && \
        git checkout -q "$BINDATA" && \
        go install ./go-bindata

# TODO: move these to Gopkg.toml?
RUN     go get github.com/golang/mock/mockgen
RUN     go get github.com/golang/protobuf/protoc-gen-go


FROM    golang:1.10-alpine
RUN     apk add -U curl git bash openssh-client make
RUN		git config --global url."https://github.com/".insteadOf 'git@github.com:'
RUN		mkdir -p /root/.ssh && ssh-keyscan github.com > /root/.ssh/known_hosts

COPY	--from=builder /go/bin /usr/local/bin
ENV     PS1="# "
WORKDIR /go/src/github.com/circleci/build-agent
ENV		BUILDTAGS="" CGO_ENABLED=0
