#!/bin/bash

exec filewatcher \
    -x '.git' \
    -x '.dobi' \
    -x 'vendor' \
    -x '**/*.swp' \
    -x '.idea' \
    -- \
    bash -c 'go test -v ./${dir} || ( echo; echo; echo; echo; exit 1 )'
