#!/usr/bin/env bash
set -e

ROOT=/tmp/containerd-dev

mkdir -p $ROOT/state $ROOT/root

export PATH=$PWD/bin/:$PATH

containerd \
    --log-level debug \
    --state $ROOT/state \
    --root $ROOT/root \
    -c default.toml
