#!/bin/bash

exec filewatcher \
    -e create -e write \
    -x 'vendor' \
    -x 'scripts' \
    -x '**/*___jb_tmp___' \
    -x '**/*___jb_old___' \
    gotestsum --format=short-verbose -- -timeout 30s './${dir}'
